spring:
  application:
    name: rxjava-service-auth
  redis:
    database: 2
    host: localhost
    port: 6379
    timeout: 100ms
  data:
    mongodb:
      database: rxjava-service-auth
      uri: mongodb://localhost:27017
server:
  port: 8080
debug: true
