spring:
  application:
    name: rxjava-service-auth
  redis:
    database: 2
    host: localhost
    port: 6379
    timeout: 100ms
  data:
    mongodb:
      database: rxjava-service-auth
      uri: mongodb://localhost:27017
  datasource:
    url: "jdbc:mysql://localhost:3306/rxjava_service_auth?createDatabaseIfNotExist=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true"
    username: root
    password: root111
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
security:
  oauth2:
    resource:
      jwt:
        key-uri: http://localhost:${server.port}/oauth/token_key
        key-value: dev
server:
  port: 8888
debug: true
management:
  endpoint:
    health:
      enabled: true