spring:
  application:
    name: rxjava-service-auth
  redis:
    database: 2
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 100ms
server:
  port: 6001
management:
  endpoint:
    health:
      enabled: true
